//
//  PlugGames.swift
//  Start.Football
//
//  Created by Vitalii Sosin on 31.01.2021.
//

import Foundation

extension Game {
    static var plugGame = Game(id: "1251-117361-137138-1212",
                               name: "Тренировка в ФОК",
                               imageStringURL: "",
                               gameNumber: "4867",
                               address: "ул. Хачтуряна, 12, стр. 2",
                               costGame: "500",
                               oneGameDate: Date(),
                               regularGame: "no",
                               listGameRegularGame: [false, false, false, false, false, false, false],
                               listDateRegularGame: [Date(), Date(), Date(), Date(), Date(), Date(), Date()],
                               miniFootball: true,
                               usualFootball: false,
                               footsal: false,
                               street: true,
                               manege: false,
                               hall: false,
                               parquet: false,
                               grass: true,
                               caoutchouc: false,
                               synthetics: false,
                               hair: false,
                               crumb: true,
                               firstTeamCount: "7",
                               secondTeamCount: "7",
                               maxCountTeams: 3,
                               maxCountPlayers: 15,
                               maxReservePlayers: 3,
                               privacyGame: "open",
                               dressingRooms: true,
                               showers: true,
                               typeOfParking: "Бесплатная",
                               paymentForParking: "",
                               parkingCost: "0",
                               descriptionGame: "Большое поле, разделенное на два с 4 прожекторами. Газон обновлялся два года назад в связи с подготовкой к ЧМ. Есть 4 типа ворот: большие, средние, мини-футбольные и для игры в панну.",
                               ownRulesGame: "Играем без подкатов. Любое попадание в руку считается нарушением. Вратарь не берет в руки от своих игроков.",
                               commentFromOrganizerGame: "Приходим за 10-15 минут. Игра начинается ровно в 21:30. Не задерживайте себя и других игроков!",
                               howMuchTimeDoWePlay: "01:00")
    
    static var plugGames = [
        Game(id: "1251-117361-137138-1212",
             name: "Тренировка в ФОК",
             imageStringURL: "",
             gameNumber: "4867",
             address: "ул. Хачтуряна, 12, стр. 2",
             costGame: "500",
             oneGameDate: Date(),
             regularGame: "no",
             listGameRegularGame: [false, false, false, false, false, false, false],
             listDateRegularGame: [Date(), Date(), Date(), Date(), Date(), Date(), Date()],
             miniFootball: true,
             usualFootball: false,
             footsal: false,
             street: true,
             manege: false,
             hall: false,
             parquet: false,
             grass: true,
             caoutchouc: false,
             synthetics: false,
             hair: false,
             crumb: true,
             firstTeamCount: "7",
             secondTeamCount: "7",
             maxCountTeams: 3,
             maxCountPlayers: 15,
             maxReservePlayers: 3,
             privacyGame: "open",
             dressingRooms: true,
             showers: true,
             typeOfParking: "Бесплатная",
             paymentForParking: "",
             parkingCost: "0",
             descriptionGame: "Большое поле, разделенное на два с 4 прожекторами. Газон обновлялся два года назад в связи с подготовкой к ЧМ. Есть 4 типа ворот: большие, средние, мини-футбольные и для игры в панну.",
             ownRulesGame: "Играем без подкатов. Любое попадание в руку считается нарушением. Вратарь не берет в руки от своих игроков.",
             commentFromOrganizerGame: "Приходим за 10-15 минут. Игра начинается ровно в 21:30. Не задерживайте себя и других игроков!",
             howMuchTimeDoWePlay: "01:00"),
        Game(id: "1251-117361-137138-2222",
             name: "Автомобилист",
             imageStringURL: "",
             gameNumber: "32",
             address: "ул. Адмирала Ушакова 8",
             costGame: "500",
             oneGameDate: Date(),
             regularGame: "no",
             listGameRegularGame: [false, false, false, false, false, false, false],
             listDateRegularGame: [Date(), Date(), Date(), Date(), Date(), Date(), Date()],
             miniFootball: true,
             usualFootball: false,
             footsal: false,
             street: true,
             manege: false,
             hall: false,
             parquet: false,
             grass: true,
             caoutchouc: false,
             synthetics: false,
             hair: false,
             crumb: true,
             firstTeamCount: "7",
             secondTeamCount: "7",
             maxCountTeams: 3,
             maxCountPlayers: 15,
             maxReservePlayers: 3,
             privacyGame: "open",
             dressingRooms: true,
             showers: true,
             typeOfParking: "Бесплатная",
             paymentForParking: "",
             parkingCost: "0",
             descriptionGame: "Большое поле, разделенное на два с 4 прожекторами. Газон обновлялся два года назад в связи с подготовкой к ЧМ. Есть 4 типа ворот: большие, средние, мини-футбольные и для игры в панну.",
             ownRulesGame: "Играем без подкатов. Любое попадание в руку считается нарушением. Вратарь не берет в руки от своих игроков.",
             commentFromOrganizerGame: "Приходим за 10-15 минут. Игра начинается ровно в 21:30. Не задерживайте себя и других игроков!",
             howMuchTimeDoWePlay: "01:00"),
        Game(id: "1251-117361-137138-dss",
             name: "Campus FootZavod",
             imageStringURL: "",
             gameNumber: "32",
             address: "ул. Дубининская, 69",
             costGame: "500",
             oneGameDate: Date(),
             regularGame: "no",
             listGameRegularGame: [false, false, false, false, false, false, false],
             listDateRegularGame: [Date(), Date(), Date(), Date(), Date(), Date(), Date()],
             miniFootball: true,
             usualFootball: false,
             footsal: false,
             street: true,
             manege: false,
             hall: false,
             parquet: false,
             grass: true,
             caoutchouc: false,
             synthetics: false,
             hair: false,
             crumb: true,
             firstTeamCount: "7",
             secondTeamCount: "7",
             maxCountTeams: 3,
             maxCountPlayers: 15,
             maxReservePlayers: 3,
             privacyGame: "open",
             dressingRooms: true,
             showers: true,
             typeOfParking: "Бесплатная",
             paymentForParking: "",
             parkingCost: "0",
             descriptionGame: "Большое поле, разделенное на два с 4 прожекторами. Газон обновлялся два года назад в связи с подготовкой к ЧМ. Есть 4 типа ворот: большие, средние, мини-футбольные и для игры в панну.",
             ownRulesGame: "Играем без подкатов. Любое попадание в руку считается нарушением. Вратарь не берет в руки от своих игроков.",
             commentFromOrganizerGame: "Приходим за 10-15 минут. Игра начинается ровно в 21:30. Не задерживайте себя и других игроков!",
             howMuchTimeDoWePlay: "01:00"),
        Game(id: "1251-117361-137138-dss",
             name: "Новые Химки. Поляна №2",
             imageStringURL: "",
             gameNumber: "32",
             address: "Химки, ул. Машинцева, 2",
             costGame: "500",
             oneGameDate: Date(),
             regularGame: "no",
             listGameRegularGame: [false, false, false, false, false, false, false],
             listDateRegularGame: [Date(), Date(), Date(), Date(), Date(), Date(), Date()],
             miniFootball: true,
             usualFootball: false,
             footsal: false,
             street: true,
             manege: false,
             hall: false,
             parquet: false,
             grass: true,
             caoutchouc: false,
             synthetics: false,
             hair: false,
             crumb: true,
             firstTeamCount: "7",
             secondTeamCount: "7",
             maxCountTeams: 3,
             maxCountPlayers: 15,
             maxReservePlayers: 3,
             privacyGame: "open",
             dressingRooms: true,
             showers: true,
             typeOfParking: "Бесплатная",
             paymentForParking: "",
             parkingCost: "0",
             descriptionGame: "Большое поле, разделенное на два с 4 прожекторами. Газон обновлялся два года назад в связи с подготовкой к ЧМ. Есть 4 типа ворот: большие, средние, мини-футбольные и для игры в панну.",
             ownRulesGame: "Играем без подкатов. Любое попадание в руку считается нарушением. Вратарь не берет в руки от своих игроков.",
             commentFromOrganizerGame: "Приходим за 10-15 минут. Игра начинается ровно в 21:30. Не задерживайте себя и других игроков!",
             howMuchTimeDoWePlay: "01:00")
    ]
}
