//
//  PlugPlayers.swift
//  Start.Football
//
//  Created by Vitalii Sosin on 31.01.2021.
//

import Foundation

extension Player {
    static var plugPlayer = Player(id: "23648-42423423",
                                   name: "Юрий",
                                   surname: "Долговязов",
                                   sex: "М",
                                   login: "Yirii",
                                   mail: "Yirii@mail.ru",
                                   password: "svsvsvsvsvs",
                                   tShirtNumber: "17",
                                   position: "ФРВ",
                                   avatarStringURL: "testOrganizator",
                                   weight: "65",
                                   growth: "175",
                                   age: "25",
                                   city: "Moscow",
                                   aboutMe: "",
                                   takePart: "60",
                                   organized: "20",
                                   phoneNumber: "+7-999-999-99-99",
                                   rating: "",
                                   payment: "")
    
    static var plugPlayers = [
        Player(id: "23648-424sd23423",
               name: "Юрий",
               surname: "Долговязов",
               sex: "М",
               login: "Yirii",
               mail: "Yirii@mail.ru",
               password: "svsvsvsvsvs",
               tShirtNumber: "17",
               position: "ФРВ",
               avatarStringURL: "testOrganizator",
               weight: "65",
               growth: "175",
               age: "25",
               city: "Moscow",
               aboutMe: "",
               takePart: "60",
               organized: "20",
               phoneNumber: "+7-999-999-99-99",
               rating: "",
               payment: ""),
        Player(id: "23648-42dv423423",
               name: "Юрий",
               surname: "Долговязов",
               sex: "М",
               login: "Yirii",
               mail: "Yirii@mail.ru",
               password: "svsvsvsvsvs",
               tShirtNumber: "17",
               position: "Защитник, полузащитник, нападающий",
               avatarStringURL: "testOrganizator",
               weight: "65",
               growth: "175",
               age: "25",
               city: "Moscow",
               aboutMe: "",
               takePart: "60",
               organized: "20",
               phoneNumber: "+7-999-999-99-99",
               rating: "",
               payment: ""),
        Player(id: "23648-424234df23",
               name: "Юрий",
               surname: "Долговязов",
               sex: "М",
               login: "Yirii",
               mail: "Yirii@mail.ru",
               password: "svsvsvsvsvs",
               tShirtNumber: "17",
               position: "Вратарь",
               avatarStringURL: "testOrganizator",
               weight: "65",
               growth: "175",
               age: "25",
               city: "Moscow",
               aboutMe: "",
               takePart: "60",
               organized: "20",
               phoneNumber: "+7-999-999-99-99",
               rating: "",
               payment: ""),
        Player(id: "23648-424234df23",
               name: "Юрий",
               surname: "Долговязов",
               sex: "М",
               login: "Yirii",
               mail: "Yirii@mail.ru",
               password: "svsvsvsvsvs",
               tShirtNumber: "17",
               position: "Вратарь",
               avatarStringURL: "testOrganizator",
               weight: "65",
               growth: "175",
               age: "25",
               city: "Moscow",
               aboutMe: "",
               takePart: "60",
               organized: "20",
               phoneNumber: "+7-999-999-99-99",
               rating: "",
               payment: "")
    ]
}
